use_frameworks!
source 'https://github.com/hnlxf/mySDK.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'mySDK_Example' do
  pod 'mySDK', :path => '../'

  target 'mySDK_Tests' do
    inherit! :search_paths

    
  end
end
